CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE cards (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       card_number VARCHAR(255) NOT NULL,
                       owner_name VARCHAR(255) NOT NULL,
                       expiration_date DATE NOT NULL,
                       status VARCHAR(50) NOT NULL,
                       balance DECIMAL(19,2) NOT NULL,
                       user_id BIGINT NOT NULL,
                       CONSTRAINT fk_card_user FOREIGN KEY (user_id) REFERENCES users(id)
);
